const express = require('express')
const router = express.Router()

const appRoute = require('./appRoute')
const authRoute = require('./authRoute')
const exposantRoute = require('./exposantRoute')
const eventRoute = require('./eventRoute')
const userRoute = require('./userRoute')
const mainServerRoute = require('./mainServerRoute')
const notificationRoute = require('./notificationRoute')
const likeRoute = require('./likeRoute')
const commentRoute = require('./commentRoute')
const testRoute = require('./testRoute')
const unifiedRoute = require('./unifiedRoute')
const manageRoute = require('./manageRoute')
const notificationController = require('../controllers/appController')

router.use('/app', appRoute)
router.use('/auth', authRoute)
router.use('/exposant', exposantRoute)
router.use('/event', eventRoute)
router.use('/user', userRoute)
router.use('/main-server', mainServerRoute)
router.use('/notification', notificationRoute)
router.use('/manage', manageRoute)
router.post('/registerNotificationToken', notificationController.registerNotificationToken)
// router.use('/test', testRoute) // SEULEMENT POUR LES TESTs
router.use('/', unifiedRoute)

module.exports = router